import {
    Alignment,
    BalloonToolbar,
    Autoformat,
    AutoImage,
    Autosave,
    BalloonEditor,
    Base64UploadAdapter,
    BlockQuote,
    Bold,
    AutoLink,
    Bookmark, CKBox, CKBoxImageEdit,
    CKFinderUploadAdapter,
    ClassicEditor,
    CloudServices,
    Code,
    CodeBlock,
    DecoupledEditor,
    Essentials,
    FindAndReplace,
    FontBackgroundColor,
    FontColor,
    FontFamily,
    FontSize,
    FullPage,
    GeneralHtmlSupport,
    Heading,
    Highlight,
    HorizontalLine,
    HtmlComment,
    HtmlEmbed,
    ImageBlock,
    ImageCaption,
    ImageInline,
    ImageInsert,
    ImageInsertViaUrl,
    ImageResize,
    ImageStyle,
    ImageTextAlternative,
    ImageToolbar,
    ImageUpload,
    Indent,
    IndentBlock,
    InlineEditor,
    Italic,
    Link,
    LinkImage,
    List,
    ListProperties,
    Markdown,
    MediaEmbed,
    Mention,
    Minimap,
    MultiRootEditor,
    PageBreak,
    Paragraph, PasteFromMarkdownExperimental,
    PasteFromOffice,
    RemoveFormat,
    SelectAll,
    ShowBlocks,
    SourceEditing,
    SpecialCharacters,
    SpecialCharactersArrows,
    SpecialCharactersCurrency,
    SpecialCharactersEssentials,
    SpecialCharactersLatin,
    SpecialCharactersMathematical,
    SpecialCharactersText,
    Strikethrough,
    Style,
    Subscript,
    Superscript,
    Table,
    TableCaption,
    TableCellProperties,
    TableColumnResize,
    TableProperties,
    TableToolbar,
    TextPartLanguage,
    TextTransformation, Title,
    TodoList,
    Underline,
    Undo,
    Widget,
    WordCount,
    BlockToolbar,
    Fullscreen,
    TableLayout
} from "ckeditor5";
import {
    AIAssistant,
    AWSTextAdapter,
    CaseChange,
    Comments,
    DocumentOutline,
    ExportPdf,
    ExportWord,
    FormatPainter,
    ImportWord,
    MergeFields,
    MultiLevelList,
    OpenAITextAdapter,
    Pagination,
    PasteFromOfficeEnhanced,
    PresenceList,
    RealTimeCollaborativeComments,
    RealTimeCollaborativeEditing,
    RealTimeCollaborativeRevisionHistory,
    RealTimeCollaborativeTrackChanges,
    RevisionHistory,
    SlashCommand,
    TableOfContents, Template, TrackChanges, TrackChangesData,
    ExportInlineStyles,
    EmailConfigurationHelper,
    Footnotes, FootnotesProperties
} from "ckeditor5-premium-features";

import  SourceEditingCodeMirror  from "@lstsystems/ckeditor5-source-editing-codemirror";

export const corePlugins: { [key: string]: any } = {
    "CKFinderUploadAdapter": CKFinderUploadAdapter,
    "Alignment": Alignment,
    "Autoformat": Autoformat,
    "AutoImage": AutoImage,
    "Autosave": Autosave,
    "Base64UploadAdapter": Base64UploadAdapter,
    "BlockQuote": BlockQuote,
    "Bold": Bold,
    "Bookmark": Bookmark,
    "CloudServices": CloudServices,
    "Code": Code,
    "CodeBlock": CodeBlock,
    "Essentials": Essentials,
    "FindAndReplace": FindAndReplace,
    "FontBackgroundColor": FontBackgroundColor,
    "FontColor": FontColor,
    "FontFamily": FontFamily,
    "FontSize": FontSize,
    "FullPage": FullPage,
    "GeneralHtmlSupport": GeneralHtmlSupport,
    "Heading": Heading,
    "Highlight": Highlight,
    "HorizontalLine": HorizontalLine,
    "HtmlComment": HtmlComment,
    "HtmlEmbed": HtmlEmbed,
    "ImageBlock": ImageBlock,
    "ImageCaption": ImageCaption,
    "ImageInline": ImageInline,
    "ImageInsert": ImageInsert,
    "ImageInsertViaUrl": ImageInsertViaUrl,
    "ImageResize": ImageResize,
    "ImageStyle": ImageStyle,
    "ImageTextAlternative": ImageTextAlternative,
    "ImageToolbar": ImageToolbar,
    "ImageUpload": ImageUpload,
    "Indent": Indent,
    "IndentBlock": IndentBlock,
    "Italic": Italic,
    "Link": Link,
    "AutoLink": AutoLink,
    "LinkImage": LinkImage,
    "List": List,
    "ListProperties": ListProperties,
    "MediaEmbed": MediaEmbed,
    "PageBreak": PageBreak,
    "Paragraph": Paragraph,
    "PasteFromOffice": PasteFromOffice,
    "RemoveFormat": RemoveFormat,
    "ShowBlocks": ShowBlocks,
    "SourceEditing": SourceEditing,
    "SpecialCharacters": SpecialCharacters,
    "SpecialCharactersArrows": SpecialCharactersArrows,
    "SpecialCharactersCurrency": SpecialCharactersCurrency,
    "SpecialCharactersEssentials": SpecialCharactersEssentials,
    "SpecialCharactersLatin": SpecialCharactersLatin,
    "SpecialCharactersMathematical": SpecialCharactersMathematical,
    "SpecialCharactersText": SpecialCharactersText,
    "Strikethrough": Strikethrough,
    "Style": Style,
    "Subscript": Subscript,
    "Superscript": Superscript,
    "Table": Table,
    "TableCaption": TableCaption,
    "TableCellProperties": TableCellProperties,
    "TableColumnResize": TableColumnResize,
    "TableProperties": TableProperties,
    "TableToolbar": TableToolbar,
    "TextTransformation": TextTransformation,
    "TodoList": TodoList,
    "Underline": Underline,
    "WordCount": WordCount,
    "BalloonEditor": BalloonEditor,
    "ClassicEditor": ClassicEditor,
    "DecoupledEditor": DecoupledEditor,
    "InlineEditor": InlineEditor,
    "MultiRootEditor": MultiRootEditor,
    "Markdown": Markdown,
    "Mention": Mention,
    "Minimap": Minimap,
    "SelectAll": SelectAll,
    "Undo": Undo,
    "Widget": Widget,
    "TextPartLanguage": TextPartLanguage,
    "Title": Title,
    "PasteFromMarkdownExperimental": PasteFromMarkdownExperimental,
    "BalloonToolbar": BalloonToolbar,
    "BlockToolbar": BlockToolbar,
    "Fullscreen": Fullscreen,
    "TableLayout": TableLayout,
};


// For future use of premium plugins
export const premiumPlugins: { [key: string]: any } = {
    "CKBox": CKBox,
    "CKBoxImageEdit": CKBoxImageEdit,
    "AIAssistant": AIAssistant,
    "OpenAITextAdapter": OpenAITextAdapter,
    "AWSTextAdapter": AWSTextAdapter,
    "CaseChange": CaseChange,
    "DocumentOutline": DocumentOutline,
    "Comments": Comments,
    "ExportPdf": ExportPdf,
    "ExportWord": ExportWord,
    "FormatPainter": FormatPainter,
    "ImportWord": ImportWord,
    "MergeFields": MergeFields,
    "MultiLevelList": MultiLevelList,
    "PasteFromOfficeEnhanced": PasteFromOfficeEnhanced,
    "SlashCommand": SlashCommand,
    "TableOfContents": TableOfContents,
    "PresenceList":PresenceList,
    "RevisionHistory":RevisionHistory,
    "RealTimeCollaborativeComments":RealTimeCollaborativeComments,
    "RealTimeCollaborativeEditing":RealTimeCollaborativeEditing,
    "RealTimeCollaborativeRevisionHistory":RealTimeCollaborativeRevisionHistory,
    "RealTimeCollaborativeTrackChanges":RealTimeCollaborativeTrackChanges,
    "TrackChanges": TrackChanges,
    "TrackChangesData": TrackChangesData,
    "Pagination": Pagination,
    "Template": Template,
    "ExportInlineStyles": ExportInlineStyles,
    "EmailConfigurationHelper": EmailConfigurationHelper,
    "Footnotes": Footnotes,
    "FootnotesProperties": FootnotesProperties
};

// For future use of extra plugins from the community
export const communityPlugins: { [key: string]: any } = {
    "SourceEditingCodeMirror": SourceEditingCodeMirror
};
